import { type Metadata } from "next";

import Sidebar from "~/components/sidebar";

export const metadata: Metadata = {
  title: "Morgen Calendar",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <Sidebar />
      {children}
    </>
  );
}
